-- owner: java-ticket

ALTER TABLE venue_application ADD CONSTRAINT fk_venue_application_venue FOREIGN KEY (venue_id) REFERENCES venue(id);
ALTER TABLE venue_area ADD CONSTRAINT fk_venue_area_venue FOREIGN KEY (venue_id) REFERENCES venue(id);
ALTER TABLE venue_seat ADD CONSTRAINT fk_venue_seat_venue FOREIGN KEY (venue_id) REFERENCES venue(id);
ALTER TABLE venue_seat ADD CONSTRAINT fk_venue_seat_area FOREIGN KEY (area_id) REFERENCES venue_area(id);
ALTER TABLE activity ADD CONSTRAINT fk_activity_category FOREIGN KEY (category_id) REFERENCES category(id);
ALTER TABLE activity ADD CONSTRAINT fk_activity_artist FOREIGN KEY (artist_id) REFERENCES artist(id);
ALTER TABLE session ADD CONSTRAINT fk_session_activity FOREIGN KEY (activity_id) REFERENCES activity(id);
ALTER TABLE session ADD CONSTRAINT fk_session_venue FOREIGN KEY (venue_id) REFERENCES venue(id);
ALTER TABLE ticket_type ADD CONSTRAINT fk_ticket_type_session FOREIGN KEY (session_id) REFERENCES session(id);
ALTER TABLE reservation ADD CONSTRAINT fk_reservation_session FOREIGN KEY (session_id) REFERENCES session(id);
ALTER TABLE seat ADD CONSTRAINT fk_seat_session FOREIGN KEY (session_id) REFERENCES session(id);
ALTER TABLE seat ADD CONSTRAINT fk_seat_ticket_type FOREIGN KEY (ticket_type_id) REFERENCES ticket_type(id);
ALTER TABLE session_seat ADD CONSTRAINT fk_session_seat_session FOREIGN KEY (session_id) REFERENCES session(id);
ALTER TABLE session_seat ADD CONSTRAINT fk_session_seat_venue FOREIGN KEY (venue_id) REFERENCES venue(id);
ALTER TABLE session_seat ADD CONSTRAINT fk_session_seat_area FOREIGN KEY (area_id) REFERENCES venue_area(id);
ALTER TABLE session_seat ADD CONSTRAINT fk_session_seat_venue_seat FOREIGN KEY (venue_seat_id) REFERENCES venue_seat(id);
ALTER TABLE session_seat ADD CONSTRAINT fk_session_seat_ticket_type FOREIGN KEY (ticket_type_id) REFERENCES ticket_type(id);
ALTER TABLE ticket_type_area ADD CONSTRAINT fk_ticket_type_area_ticket_type FOREIGN KEY (ticket_type_id) REFERENCES ticket_type(id);
ALTER TABLE ticket_type_area ADD CONSTRAINT fk_ticket_type_area_session FOREIGN KEY (session_id) REFERENCES session(id);
ALTER TABLE ticket_type_area ADD CONSTRAINT fk_ticket_type_area_area FOREIGN KEY (area_id) REFERENCES venue_area(id);
ALTER TABLE stock_log ADD CONSTRAINT fk_stock_log_session FOREIGN KEY (session_id) REFERENCES session(id);
ALTER TABLE stock_log ADD CONSTRAINT fk_stock_log_ticket_type FOREIGN KEY (ticket_type_id) REFERENCES ticket_type(id);
ALTER TABLE venue_seat_layout_template ADD CONSTRAINT fk_template_venue FOREIGN KEY (venue_id) REFERENCES venue(id);
ALTER TABLE venue_seat_layout_template_section ADD CONSTRAINT fk_template_section_template FOREIGN KEY (template_id) REFERENCES venue_seat_layout_template(id) ON DELETE CASCADE;
ALTER TABLE venue_default_layout ADD CONSTRAINT fk_venue_default_layout_venue FOREIGN KEY (venue_id) REFERENCES venue(id);
ALTER TABLE venue_default_layout_section ADD CONSTRAINT fk_venue_default_section_layout FOREIGN KEY (default_layout_id) REFERENCES venue_default_layout(id) ON DELETE CASCADE;
ALTER TABLE activity_seat_layout ADD CONSTRAINT fk_activity_layout_activity FOREIGN KEY (activity_id) REFERENCES activity(id) ON DELETE CASCADE;
ALTER TABLE activity_seat_layout ADD CONSTRAINT fk_activity_layout_template FOREIGN KEY (source_template_id) REFERENCES venue_seat_layout_template(id);
ALTER TABLE activity_seat_layout_section ADD CONSTRAINT fk_activity_section_layout FOREIGN KEY (activity_layout_id) REFERENCES activity_seat_layout(id) ON DELETE CASCADE;
ALTER TABLE activity_seat_layout_section ADD CONSTRAINT fk_activity_section_template_section FOREIGN KEY (source_template_section_id) REFERENCES venue_seat_layout_template_section(id);
ALTER TABLE session_seat_layout ADD CONSTRAINT fk_session_layout_session FOREIGN KEY (session_id) REFERENCES session(id) ON DELETE CASCADE;
ALTER TABLE session_seat_layout ADD CONSTRAINT fk_session_layout_activity_layout FOREIGN KEY (activity_layout_id) REFERENCES activity_seat_layout(id);
ALTER TABLE session_seat_layout ADD CONSTRAINT fk_session_layout_template FOREIGN KEY (source_template_id) REFERENCES venue_seat_layout_template(id);
ALTER TABLE session_seat_layout_section ADD CONSTRAINT fk_session_section_layout FOREIGN KEY (session_layout_id) REFERENCES session_seat_layout(id) ON DELETE CASCADE;
ALTER TABLE session_seat_layout_section ADD CONSTRAINT fk_session_section_activity_section FOREIGN KEY (activity_layout_section_id) REFERENCES activity_seat_layout_section(id);
ALTER TABLE session_seat_layout_section ADD CONSTRAINT fk_session_section_template_section FOREIGN KEY (source_template_section_id) REFERENCES venue_seat_layout_template_section(id);
ALTER TABLE session_seat_layout_section ADD CONSTRAINT fk_session_section_ticket_type FOREIGN KEY (ticket_type_id) REFERENCES ticket_type(id);
ALTER TABLE session_seat ADD CONSTRAINT fk_session_seat_layout_section FOREIGN KEY (layout_section_id) REFERENCES session_seat_layout_section(id);
ALTER TABLE seat_override ADD CONSTRAINT fk_seat_override_block FOREIGN KEY (seat_block_id) REFERENCES seat_block(id);
ALTER TABLE station ADD CONSTRAINT fk_station_tour FOREIGN KEY (tour_id) REFERENCES tour(id);

CREATE INDEX IF NOT EXISTS idx_venue_application_applicant ON venue_application(applicant_id);
CREATE INDEX IF NOT EXISTS idx_venue_application_status ON venue_application(status);
CREATE INDEX IF NOT EXISTS idx_venue_application_create_time ON venue_application(create_time DESC);
CREATE INDEX IF NOT EXISTS idx_venue_area_venue ON venue_area(venue_id);
CREATE INDEX IF NOT EXISTS idx_venue_area_status ON venue_area(status);
CREATE INDEX IF NOT EXISTS idx_venue_seat_venue ON venue_seat(venue_id);
CREATE INDEX IF NOT EXISTS idx_venue_seat_area ON venue_seat(area_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_venue_seat_area_position ON venue_seat(area_id, row_no, seat_no) WHERE status = 1;
CREATE INDEX IF NOT EXISTS idx_session_seat_session ON session_seat(session_id);
CREATE INDEX IF NOT EXISTS idx_session_seat_venue ON session_seat(venue_id);
CREATE INDEX IF NOT EXISTS idx_session_seat_area ON session_seat(area_id);
CREATE INDEX IF NOT EXISTS idx_session_seat_status ON session_seat(status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_session_seat_session_venue_seat ON session_seat(session_id, venue_seat_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_session_seat_layout_position ON session_seat(session_id, layout_section_id, row_no, seat_no) WHERE layout_section_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ticket_type_area_ticket_type ON ticket_type_area(ticket_type_id);
CREATE INDEX IF NOT EXISTS idx_ticket_type_area_session ON ticket_type_area(session_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ticket_type_area_session_area_unique ON ticket_type_area(session_id, area_id);
CREATE INDEX IF NOT EXISTS idx_stock_log_session ON stock_log(session_id);
CREATE INDEX IF NOT EXISTS idx_reservation_user ON reservation(user_id);
CREATE INDEX IF NOT EXISTS idx_session_activity ON session(activity_id);
CREATE INDEX IF NOT EXISTS idx_ticket_type_session ON ticket_type(session_id);
CREATE INDEX IF NOT EXISTS idx_seat_session ON seat(session_id);
CREATE INDEX IF NOT EXISTS idx_seat_ticket_type ON seat(ticket_type_id);
CREATE INDEX IF NOT EXISTS idx_venue_seat_layout_template_venue ON venue_seat_layout_template(venue_id);
CREATE INDEX IF NOT EXISTS idx_template_section_template ON venue_seat_layout_template_section(template_id);
CREATE INDEX IF NOT EXISTS idx_activity_seat_layout_activity ON activity_seat_layout(activity_id);
CREATE INDEX IF NOT EXISTS idx_activity_section_layout ON activity_seat_layout_section(activity_layout_id);
CREATE INDEX IF NOT EXISTS idx_session_seat_layout_session ON session_seat_layout(session_id);
CREATE INDEX IF NOT EXISTS idx_session_section_layout ON session_seat_layout_section(session_layout_id);
CREATE INDEX IF NOT EXISTS idx_session_section_ticket_type ON session_seat_layout_section(ticket_type_id);
CREATE INDEX IF NOT EXISTS idx_session_seat_layout_section ON session_seat(layout_section_id);
