spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
