export const GRAB_STATUS = {
  QUEUED: 'QUEUED',
  WAITING: 'WAITING',
  TRYING_TICKET_TYPE: 'TRYING_TICKET_TYPE',
  LOCKING: 'LOCKING',
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  ORDER_CREATING: 'ORDER_CREATING',
  ORDER_CREATED: 'ORDER_CREATED',
  SOLD_OUT: 'SOLD_OUT',
  DOWNGRADING: 'DOWNGRADING',
  LIMITED: 'LIMITED',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED',
} as const;

export type GrabStatus = (typeof GRAB_STATUS)[keyof typeof GRAB_STATUS];

const TERMINAL_STATUSES = new Set<GrabStatus>([
  GRAB_STATUS.ORDER_CREATED,
  GRAB_STATUS.SOLD_OUT,
  GRAB_STATUS.LIMITED,
  GRAB_STATUS.FAILED,
  GRAB_STATUS.EXPIRED,
]);

const QUEUE_PROGRESS_STATUSES = new Set<GrabStatus>([
  GRAB_STATUS.QUEUED,
  GRAB_STATUS.WAITING,
  GRAB_STATUS.TRYING_TICKET_TYPE,
  GRAB_STATUS.LOCKING,
  GRAB_STATUS.ORDER_CREATING,
  GRAB_STATUS.ORDER_CREATED,
  GRAB_STATUS.SOLD_OUT,
  GRAB_STATUS.DOWNGRADING,
  GRAB_STATUS.FAILED,
  GRAB_STATUS.LIMITED,
  GRAB_STATUS.EXPIRED,
]);

export function isTerminalGrabStatus(status: GrabStatus): boolean {
  return TERMINAL_STATUSES.has(status);
}

export function isQueueProgressStatus(status: GrabStatus): boolean {
  return QUEUE_PROGRESS_STATUSES.has(status);
}
