server:
  port: 8081

spring:
  application:
    name: java-user
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/omni_ticket
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
      config:
        import-check:
          enabled: false
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        file-extension: yaml
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:localhost:8858}
        port: ${SENTINEL_USER_TRANSPORT_PORT:8720}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
