spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
